Importing Libraries

In [35]:
#required libraries
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from keras.preprocessing.text import Tokenizer
from keras.utils import to_categorical
import numpy as np
import torch
     

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Loading Dataset

In [2]:
path = '/content/1661-0.txt'
corpus = open(path).read().lower()
print('corpus length:', len(corpus))

corpus length: 46278


In [3]:
#preprocess the corpus
import re
corpus=corpus.lower()
clean_corpus=re.sub('[^a-z0-9]+',' ', corpus)

In [4]:
clean_corpus


' project gutenberg s the adventures of sherlock holmes by arthur conan doyle this ebook is for the use of anyone anywhere at no cost and with almost no restrictions whatsoever you may copy it give it away or re use it under the terms of the project gutenberg license included with this ebook or online at www gutenberg net title the adventures of sherlock holmes author arthur conan doyle release date november 29 2002 ebook 1661 last updated may 20 2019 language english character set encoding utf 8 start of this project gutenberg ebook the adventures of sherlock holmes produced by an anonymous project gutenberg volunteer and jose menendez cover the adventures of sherlock holmes by arthur conan doyle contents i a scandal in bohemia ii the red headed league iii a case of identity iv the boscombe valley mystery v the five orange pips vi the man with the twisted lip vii the adventure of the blue carbuncle viii the adventure of the speckled band ix the adventure of the engineer s thumb x the 

In [5]:

#tokenizing the text into words
tokens = word_tokenize(clean_corpus)
tokens


['project',
 'gutenberg',
 's',
 'the',
 'adventures',
 'of',
 'sherlock',
 'holmes',
 'by',
 'arthur',
 'conan',
 'doyle',
 'this',
 'ebook',
 'is',
 'for',
 'the',
 'use',
 'of',
 'anyone',
 'anywhere',
 'at',
 'no',
 'cost',
 'and',
 'with',
 'almost',
 'no',
 'restrictions',
 'whatsoever',
 'you',
 'may',
 'copy',
 'it',
 'give',
 'it',
 'away',
 'or',
 're',
 'use',
 'it',
 'under',
 'the',
 'terms',
 'of',
 'the',
 'project',
 'gutenberg',
 'license',
 'included',
 'with',
 'this',
 'ebook',
 'or',
 'online',
 'at',
 'www',
 'gutenberg',
 'net',
 'title',
 'the',
 'adventures',
 'of',
 'sherlock',
 'holmes',
 'author',
 'arthur',
 'conan',
 'doyle',
 'release',
 'date',
 'november',
 '29',
 '2002',
 'ebook',
 '1661',
 'last',
 'updated',
 'may',
 '20',
 '2019',
 'language',
 'english',
 'character',
 'set',
 'encoding',
 'utf',
 '8',
 'start',
 'of',
 'this',
 'project',
 'gutenberg',
 'ebook',
 'the',
 'adventures',
 'of',
 'sherlock',
 'holmes',
 'produced',
 'by',
 'an',
 'ano

In [6]:
#length of the sequence to train
train_len = 3

In [7]:

#converting the data into required sequence
text_sequences = []
for i in range(train_len,len(tokens)+1):
  seq = tokens[i-train_len:i]
  text_sequences.append(seq)
     

In [8]:
text_sequences


[['project', 'gutenberg', 's'],
 ['gutenberg', 's', 'the'],
 ['s', 'the', 'adventures'],
 ['the', 'adventures', 'of'],
 ['adventures', 'of', 'sherlock'],
 ['of', 'sherlock', 'holmes'],
 ['sherlock', 'holmes', 'by'],
 ['holmes', 'by', 'arthur'],
 ['by', 'arthur', 'conan'],
 ['arthur', 'conan', 'doyle'],
 ['conan', 'doyle', 'this'],
 ['doyle', 'this', 'ebook'],
 ['this', 'ebook', 'is'],
 ['ebook', 'is', 'for'],
 ['is', 'for', 'the'],
 ['for', 'the', 'use'],
 ['the', 'use', 'of'],
 ['use', 'of', 'anyone'],
 ['of', 'anyone', 'anywhere'],
 ['anyone', 'anywhere', 'at'],
 ['anywhere', 'at', 'no'],
 ['at', 'no', 'cost'],
 ['no', 'cost', 'and'],
 ['cost', 'and', 'with'],
 ['and', 'with', 'almost'],
 ['with', 'almost', 'no'],
 ['almost', 'no', 'restrictions'],
 ['no', 'restrictions', 'whatsoever'],
 ['restrictions', 'whatsoever', 'you'],
 ['whatsoever', 'you', 'may'],
 ['you', 'may', 'copy'],
 ['may', 'copy', 'it'],
 ['copy', 'it', 'give'],
 ['it', 'give', 'it'],
 ['give', 'it', 'away'],
 ['it',

In [9]:
#converting the texts into integer sequence
tokenizer = Tokenizer()
tokenizer.fit_on_texts(text_sequences)
sequences = tokenizer.texts_to_sequences(text_sequences)
sequences

[[337, 248, 59],
 [248, 59, 1],
 [59, 1, 249],
 [1, 249, 4],
 [249, 4, 79],
 [4, 79, 26],
 [79, 26, 36],
 [26, 36, 338],
 [36, 338, 339],
 [338, 339, 340],
 [339, 340, 32],
 [340, 32, 250],
 [32, 250, 14],
 [250, 14, 27],
 [14, 27, 1],
 [27, 1, 200],
 [1, 200, 4],
 [200, 4, 484],
 [4, 484, 773],
 [484, 773, 18],
 [773, 18, 68],
 [18, 68, 774],
 [68, 774, 2],
 [774, 2, 16],
 [2, 16, 251],
 [16, 251, 68],
 [251, 68, 775],
 [68, 775, 776],
 [775, 776, 9],
 [776, 9, 60],
 [9, 60, 777],
 [60, 777, 8],
 [777, 8, 201],
 [8, 201, 8],
 [201, 8, 156],
 [8, 156, 56],
 [156, 56, 778],
 [56, 778, 200],
 [778, 200, 8],
 [200, 8, 118],
 [8, 118, 1],
 [118, 1, 779],
 [1, 779, 4],
 [779, 4, 1],
 [4, 1, 337],
 [1, 337, 248],
 [337, 248, 485],
 [248, 485, 780],
 [485, 780, 16],
 [780, 16, 32],
 [16, 32, 250],
 [32, 250, 56],
 [250, 56, 781],
 [56, 781, 18],
 [781, 18, 782],
 [18, 782, 248],
 [782, 248, 783],
 [248, 783, 341],
 [783, 341, 1],
 [341, 1, 249],
 [1, 249, 4],
 [249, 4, 79],
 [4, 79, 26],
 [79

In [10]:
sequences=np.asarray(sequences)

In [11]:
#vocabulary size
vocabulary_size = len(tokenizer.word_counts)+1
vocabulary_size

1966

In [12]:
#trainX
train_inputs=sequences[:,:-1]

In [13]:
train_inputs


array([[ 337,  248],
       [ 248,   59],
       [  59,    1],
       ...,
       [1965,  341],
       [ 341,    4],
       [   4,    1]])

In [14]:

#input sequence length 
seq_length=train_inputs.shape[1]
seq_length


2

In [15]:
#trainY
train_targets=sequences[:,-1]

In [16]:
train_targets
     


array([ 59,   1, 249, ...,   4,   1,  99])

In [17]:
#one hot encoding
train_targets = to_categorical(train_targets, num_classes=vocabulary_size)

In [18]:

train_targets

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [19]:

#required libraries
import torch
from torch.optim import Adam
import torch.nn as nn

In [20]:
#lstm model
class lstm(nn.Module):
    def __init__(self, vocab_size, embed_size, hidden_size):
        super().__init__()
        #simple lookup table that stores embeddings of a fixed dictionary and size.
        self.embed = nn.Embedding(vocab_size, embed_size)
        
        #lstm 
        self.lstm = nn.LSTM(embed_size, hidden_size, num_layers=2, bidirectional=False)
        
        #fully connected layer
        self.linear = nn.Linear(hidden_size*seq_length,vocab_size)
    
    def forward(self, input_word):
        #input sequence to embeddings
        embedded = self.embed(input_word)
        
        #passing the embedding to lstm model
        output, hidden = self.lstm(embedded)
        
        #reshaping
        output=output.view(output.size(0), -1)
        
        #fully connected layer
        output = self.linear(output)
        return output,hidden


In [21]:
model=lstm(vocab_size=vocabulary_size,embed_size=128, hidden_size=256)
model

lstm(
  (embed): Embedding(1966, 128)
  (lstm): LSTM(128, 256, num_layers=2)
  (linear): Linear(in_features=512, out_features=1966, bias=True)
)

In [22]:
#Adam optimizer
optimizer= Adam(model.parameters(), lr=0.07)

#loss
criterion = nn.BCEWithLogitsLoss()

In [23]:

#training the model
def train(epoch):
    #set the model to train
    model.train()
    tr_loss=0    
    
    #clearing the Gradients 
    optimizer.zero_grad()
    
    #predict the output
    y_pred, (state_h, state_c) = model(torch.from_numpy(train_inputs))
    
    #compute the loss
    loss=criterion(y_pred,torch.from_numpy(train_targets))
    losses.append(loss)
    
    #backpropagate
    loss.backward()

    #update the parameters
    optimizer.step()
    tr_loss = loss.item()

    print("Epoch : ",epoch,"loss : ",loss)
     

In [24]:

#number of epoch
no_epoch=40
losses=[]
for epoch in range(1,no_epoch+1):
    train(epoch)

Epoch :  1 loss :  tensor(0.6937, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  2 loss :  tensor(0.0077, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  3 loss :  tensor(0.0067, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  4 loss :  tensor(0.0134, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  5 loss :  tensor(0.0073, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  6 loss :  tensor(0.0075, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  7 loss :  tensor(0.0063, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  8 loss :  tensor(0.0891, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  9 loss :  tensor(0.0076, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  10 loss :  tensor(0.0096, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  11 loss :  tensor(0.0111, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
Epoch :  12 loss :  tensor(0.0120, grad_fn=<BinaryCrossEntropyWithLogitsBackward0>)
E

In [27]:

def predict_next_word(text):
    #set the model to evaluation
    model.eval()

    #preprocess
    text = text.lower().strip()
    
    #converting the text to word tokens
    input_tokens = word_tokenize(text)
    
    #converting the tokens to integer sequence
    sequences = tokenizer.texts_to_sequences([input_tokens])
    
    #converting to array
    sequences=np.asarray(sequences)
    with torch.no_grad():
        #converting to tensor
        sequences=torch.from_numpy(sequences)
        #predicting the output
        predict,(hidden,cell)=model(sequences)
    
    #applying the softmax layer
    softmax = torch.exp(predict)
    prob = list(softmax.numpy())
    
    #index of the predict word
    predictions = np.argmax(prob)

    #converting the sequence back to word
    next_word=tokenizer.sequences_to_texts([[predictions]])
    return next_word

example

In [32]:
#we trained our model with sequence length of 2
input_text="give it"

In [34]:
print("Possible next word will be:")
predict_next_word(input_text)
     

Possible next word will be:


['with']